[package]
name = "MStarPlayer-mqtt-plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.28"
env_logger = "0.10.2"
rumqttc = "0.24.0"
slint = "1.14.1"

[dev-dependencies]
mockall = "0.11.4"

[lib]
crate-type=["lib", "cdylib"]
